"""adding email column to the jobseeker profile

Revision ID: 00fce9b5d253
Revises: 76548005fd6c
Create Date: 2024-11-20 15:15:31.605081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00fce9b5d253'
down_revision = '76548005fd6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobseekerprofiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobseekerprofiles', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
