"""Increase phone column size

Revision ID: 086d4f9f53e4
Revises: b929f2a35d6e
Create Date: 2024-11-16 10:23:46.318213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086d4f9f53e4'
down_revision = 'b929f2a35d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)

    # ### end Alembic commands ###
