"""renamed user_id to id

Revision ID: 68453265143f
Revises: f6a70c06ffea
Create Date: 2024-11-16 01:48:50.319686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68453265143f'
down_revision = 'f6a70c06ffea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
    
    with op.batch_alter_table('adminactions', schema=None) as batch_op:
        batch_op.drop_constraint('adminactions_target_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('adminactions_admin_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['target_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['admin_id'], ['id'])

    with op.batch_alter_table('employerprofiles', schema=None) as batch_op:
        batch_op.drop_constraint('employerprofiles_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('jobseekerprofiles', schema=None) as batch_op:
        batch_op.drop_constraint('jobseekerprofiles_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('notifications_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('payments_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), server_default=sa.text("nextval('users_user_id_seq'::regclass)"), autoincrement=True, nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('payments_user_id_fkey', 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notifications_user_id_fkey', 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('jobseekerprofiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('jobseekerprofiles_user_id_fkey', 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('employerprofiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('employerprofiles_user_id_fkey', 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('adminactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('adminactions_admin_id_fkey', 'users', ['admin_id'], ['user_id'])
        batch_op.create_foreign_key('adminactions_target_user_id_fkey', 'users', ['target_user_id'], ['user_id'])

    # ### end Alembic commands ###
