"""Add device_token to User model

Revision ID: d93be5994148
Revises: 086d4f9f53e4
Create Date: 2024-11-17 11:34:58.350705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd93be5994148'
down_revision = '086d4f9f53e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_token', sa.String(length=255), nullable=True))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=True)
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.alter_column('phone',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('device_token')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
